### ISSUE TITLE
How to ignore emails when using @ token?

### ISSUE THREAD

**Issue by naillizard** [tactivos/jquery-sew#6]
Hi there,

how to ignore email entries when using @ token?

**Comment by johnnyhalife** [comment]
You just write an email and the regExp won't match it.

**Comment by naillizard** [comment]
Hi, yes I realized I can just keep typing. But, like on github, it only match strings starting with @, avoiding autocompletion for email entries...

**Comment by jfelsinger** [comment]
Four months old, but since someone somewhere might be looking for an answer I'll have a stab at it. 

You could edit line 33 in jquery.sew.js; take the word boundary out of the matching regex. That way the token will only be matched if there is white-space in front of it, or it is the first character in the string.

```
this.expression = new RegExp('(^|\\b|\\s)' + this.options.token + '([\\w.]*)$');
```

to

```
this.expression = new RegExp('(^|\\s)' + this.options.token + '([\\w.]*)$');
```

If you don't want to edit the sew.js you can also use some of the same regex in your token like the so:

```
token: '(^|\\s)@'
```
